name: anthony

# Trigger the workflow manually or on every push
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: package anthony/helm/myapp
      run: |
        echo "package anthony/helm/myapp:"
        echo "================================================"

        if [ -d "anthony/helm/myapp" ]; then
          echo "✅ Directory exists. Contents:"
          helm package anthony/helm/myapp/
          echo ""
        else
          echo "❌ Directory 'anthony/helm/myapp' does not exist"
          echo "📂 Available directories at root level:"
          ls -la ./
        fi

    - name: test anthony/helm/myapp
      run: |
        echo "helm lint anthony/helm/myapp:"
        echo "================================================"

        helm lint anthony/helm/myapp/

    - name: ct install anthony/helm/myapp
      run: |
        echo "package anthony/helm/myapp:"
        echo "================================================"

        ct install antrhony/helm/myapp

    - name: publish anthony/helm/myapp
      run: |
        echo "package anthony/helm/myapp:"
        echo "================================================"

