name: damien

# Trigger the workflow manually or on every push
on:
  workflow_dispatch:

jobs:
  helm:
    runs-on: alpine/helm:3

    steps:
    - name: helm lint
      run: |
        helm lint damien/helm/myapp

    - name: helm unitest
      run: |:
        helm plugin install --version $HELM_UNITTEST_VERSION https://github.com/helm-unittest/helm-unittest > /dev/null
        helm unittest --strict -f 'unittests/**/*.yaml' ./charts/woodpecker/charts/server/ ./charts/woodpecker/charts/agent

    - name: helm schema
      run: |
        helm plugin install https://github.com/dadav/helm-schema > /dev/null
        helm schema damien/helm/myapp

    - name: helm package
      run: |
        helm package damien/helm/myapp
