name: damien

# Trigger the workflow manually or on every push
on:
  workflow_dispatch:

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: helm lint
        image: alpine/helm:3
        run: |
          helm lint damien/helm/myapp

      - name: helm unitest
        image: alpine/helm:3
        run: |
          helm plugin install --version $HELM_UNITTEST_VERSION https://github.com/helm-unittest/helm-unittest > /dev/null
          helm unittest --strict -f 'unittests/**/*.yaml' ./charts/woodpecker/charts/server/ ./charts/woodpecker/charts/agent

      - name: helm schema
        image: alpine/helm:3
        run: |
          helm plugin install https://github.com/dadav/helm-schema > /dev/null
          helm schema damien/helm/myapp

      - name: helm package
        image: alpine/helm:3
        run: |
          helm package damien/helm/myapp
